### ISSUE TITLE
Task: DID Resolver plugin registry

### ISSUE THREAD

**Issue by dbluhm** [rd-dlab/aries-cloudagent-python#15]
The DID Resolver Registry keeps track of the registered DID Resolvers that ACA-Py will use at runtime to resolve DIDs.

An instance of the DIDResolverReigstry component will need to be bound at startup for use in registering resolvers. Built-in resolvers should be registered on startup.

This component should:
- Allow loading resolvers as plugins (specified on the command line, through a config file, etc.)
  - Give the `--plugin` argument a python module path (`path.to.my.module`) that contains a `setup` method that looks like the following:
    ```python
    async def setup(session: ProfileSession):
        did_resolver_registry = session.inject(DIDResolverRegistry)
        did_resolver_registry.register(MyResolver(with, arguments, needed, to, instantiate))
    ```
- Provide ordering of resolvers? (native before non-native, other priorities assigned?)
- Allow multiple resolvers supporting the same methods. The most obvious case for this is when we have a native resolver for a method but also have a non-native resolver for the same method (Indy will be supported natively but is also supported by the universal resolver).

### Tasks
- [ ] Write tests
- [ ] Implement functionality
- [ ] Validate

Story: #8

**Comment by burdettadam** [comment]
`--plugin` flag is already being used for `external_plugins`. `external_plugins` are used for protocol loading with the `register_plugin` method found in plugin_registry.py. This method feels like the wrong place to register resolvers.

I propose we use something like `--did-resolvers` or `--resolver_registry` flag and create a new register method to be called in `load_plugins` from default_context.py. this is called further up the stack in `provision` from provision.py.

**Comment by dbluhm** [comment]
I think I would actually recommend the opposite. If we use the plugin flag (we've been using it for the toolbox for a fair while, I think I might have actually been the one to add it lol), then all we have to worry about is providing the registry instance to the session and providing an interface for loading an already initialized resolver into our registry. If we go the `--did-resolvers` route, to achieve the same simple setup, I think we'd be duplicating what the `--plugin` is already doing.

**Comment by burdettadam** [comment]
ok, to clarify, we should add the logic to `register_plugin` method so we can use the same `--plugin` flag. Currently, there are two paths of logic for `register_plugin`, if not registered, register a new did protocol. We will add a third branch of logic? if the loaded class has `setup`, call setup, otherwise treat it as a new did protocol plugin?

**Comment by dbluhm** [comment]
The code isn't extremely fresh in my mind but I think we should utilize the calling of `setup` path which should already be in there.

**Comment by burdettadam** [comment]
I see, I will add it. 
```
            # Any plugin with a setup method is considered valid.
            if hasattr(mod, "setup"):
                self._plugins[module_name] = mod
                return mod
```
